# Generated by Django 4.0.3 on 2022-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('North', models.FloatField()),
                ('East', models.FloatField()),
                ('West', models.FloatField()),
                ('South', models.IntegerField()),
            ],
        ),
    ]
